/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbox.proyecto;

import com.sun.jna.NativeLibrary;
import java.awt.Color;
import java.io.File;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author Álvaro Andrés Maldonado Pinto
 */
public class ReproductorSec extends javax.swing.JFrame {

    private EmbeddedMediaPlayerComponent playerFaceRecorder, playerActivityRender, playerCanalExt;
    private final String ruta = System.getProperty("user.dir") + "\\lib";
    private final File vlcInstallPath = new File(ruta);
    private File faceRecorder, activityRender, canalExt;
    private static final String NO_DISPONIBLE= "Perspectiva no configurada para este experimento";

    /**
     * Creates new form ReproductorSec
     *
     * @param faceRecorder
     * @param activityRender
     * @param canalExt
     */
    public ReproductorSec(File faceRecorder, File activityRender, File canalExt) {
        this.faceRecorder = faceRecorder;
        this.activityRender = activityRender;
        this.canalExt = canalExt;
        NativeLibrary.addSearchPath("libvlc", vlcInstallPath.getAbsolutePath());
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);//centrar en pantalla
        setBounds(0, 0, 1315, 675);
        playerFaceRecorder = new EmbeddedMediaPlayerComponent();
        playerActivityRender = new EmbeddedMediaPlayerComponent();
        playerCanalExt = new EmbeddedMediaPlayerComponent();
        //se añade reproductor 
        faceRecorderPanel.add(playerFaceRecorder);
        playerFaceRecorder.setSize(faceRecorderPanel.getSize());
        playerFaceRecorder.setVisible(true);

        activityRenderPanel.add(playerActivityRender);
        playerActivityRender.setSize(activityRenderPanel.getSize());
        playerActivityRender.setVisible(true);

        canalExtPanel.add(playerCanalExt);
        playerCanalExt.setSize(canalExtPanel.getSize());
        playerCanalExt.setVisible(true);

        if (null != faceRecorder) {
            jTextFieldFaceRecorder.setText(faceRecorder.getAbsolutePath());
        } else {
            jTextFieldFaceRecorder.setText(NO_DISPONIBLE);
            faceRecorderPanel.setBackground(Color.BLACK);
        }

        if (null != activityRender) {
            jTextFieldActivityRender.setText(activityRender.getAbsolutePath());
        } else {
            jTextFieldActivityRender.setText(NO_DISPONIBLE);
            activityRenderPanel.setBackground(Color.BLACK);
        }

        if (null != canalExt) {
            jTextFieldCanalExterno.setText(canalExt.getAbsolutePath());
        } else {
            jTextFieldCanalExterno.setText(NO_DISPONIBLE);
            canalExtPanel.setBackground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faceRecorderPanel = new javax.swing.JPanel();
        activityRenderPanel = new javax.swing.JPanel();
        canalExtPanel = new javax.swing.JPanel();
        labelFaceRecorder = new javax.swing.JLabel();
        labelActRender = new javax.swing.JLabel();
        labelCanalExt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iniButton = new javax.swing.JButton();
        PauseButton = new javax.swing.JButton();
        detButton = new javax.swing.JButton();
        jTextFieldFaceRecorder = new javax.swing.JTextField();
        jTextFieldActivityRender = new javax.swing.JTextField();
        jTextFieldCanalExterno = new javax.swing.JTextField();

        setResizable(false);

        faceRecorderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        faceRecorderPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout faceRecorderPanelLayout = new javax.swing.GroupLayout(faceRecorderPanel);
        faceRecorderPanel.setLayout(faceRecorderPanelLayout);
        faceRecorderPanelLayout.setHorizontalGroup(
            faceRecorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        faceRecorderPanelLayout.setVerticalGroup(
            faceRecorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        activityRenderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        activityRenderPanel.setPreferredSize(new java.awt.Dimension(425, 425));

        javax.swing.GroupLayout activityRenderPanelLayout = new javax.swing.GroupLayout(activityRenderPanel);
        activityRenderPanel.setLayout(activityRenderPanelLayout);
        activityRenderPanelLayout.setHorizontalGroup(
            activityRenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        activityRenderPanelLayout.setVerticalGroup(
            activityRenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        canalExtPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        canalExtPanel.setPreferredSize(new java.awt.Dimension(425, 425));

        javax.swing.GroupLayout canalExtPanelLayout = new javax.swing.GroupLayout(canalExtPanel);
        canalExtPanel.setLayout(canalExtPanelLayout);
        canalExtPanelLayout.setHorizontalGroup(
            canalExtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        canalExtPanelLayout.setVerticalGroup(
            canalExtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        labelFaceRecorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFaceRecorder.setText("FaceRecorder");

        labelActRender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelActRender.setText("ActivityRender");

        labelCanalExt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCanalExt.setText("Perspectiva Externa");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iniButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        iniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1468668624_audio-video-outline-play.png"))); // NOI18N
        iniButton.setToolTipText("Iniciar");
        iniButton.setBorder(null);
        iniButton.setBorderPainted(false);
        iniButton.setOpaque(false);
        iniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniButtonActionPerformed(evt);
            }
        });

        PauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1468668628_audio-video-outline-pause.png"))); // NOI18N
        PauseButton.setToolTipText("Pausar");
        PauseButton.setBorder(null);
        PauseButton.setBorderPainted(false);
        PauseButton.setOpaque(false);
        PauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseButtonActionPerformed(evt);
            }
        });

        detButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        detButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1468668622_audio-video-outline-stop.png"))); // NOI18N
        detButton.setToolTipText("Detener");
        detButton.setBorder(null);
        detButton.setBorderPainted(false);
        detButton.setOpaque(false);
        detButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detButton)
                    .addComponent(PauseButton)
                    .addComponent(iniButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextFieldFaceRecorder.setEditable(false);
        jTextFieldFaceRecorder.setText("jTextField1");
        jTextFieldFaceRecorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFaceRecorderActionPerformed(evt);
            }
        });

        jTextFieldActivityRender.setEditable(false);
        jTextFieldActivityRender.setText("jTextField2");

        jTextFieldCanalExterno.setEditable(false);
        jTextFieldCanalExterno.setText("jTextField3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(faceRecorderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFaceRecorder)
                    .addComponent(jTextFieldFaceRecorder, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(activityRenderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelActRender)
                            .addComponent(jTextFieldActivityRender, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCanalExt)
                            .addComponent(canalExtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCanalExterno, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFaceRecorder)
                    .addComponent(labelActRender)
                    .addComponent(labelCanalExt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(canalExtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activityRenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faceRecorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFaceRecorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldActivityRender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCanalExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniButtonActionPerformed
        // TODO add your handling code here:
        if (null != faceRecorder) {
            playerFaceRecorder.getMediaPlayer().playMedia(faceRecorder.getAbsolutePath());
        }
        if (null != activityRender) {
            playerActivityRender.getMediaPlayer().playMedia(activityRender.getAbsolutePath());
        }
        if (null != canalExt) {
            playerCanalExt.getMediaPlayer().playMedia(canalExt.getAbsolutePath());
        }
    }//GEN-LAST:event_iniButtonActionPerformed

    private void detButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detButtonActionPerformed
        // TODO add your handling code here:
        if (null != faceRecorder) {
            playerFaceRecorder.getMediaPlayer().stop();
        }
        if (null != activityRender) {
            playerActivityRender.getMediaPlayer().stop();
        }
        if (null != canalExt) {
            playerCanalExt.getMediaPlayer().stop();
        }
    }//GEN-LAST:event_detButtonActionPerformed

    private void PauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseButtonActionPerformed
        // TODO add your handling code here:
        if (null != faceRecorder) {
            playerFaceRecorder.getMediaPlayer().setPause(playerFaceRecorder.getMediaPlayer().isPlaying() ? true : false);
        }
        if (null != activityRender) {
            playerActivityRender.getMediaPlayer().setPause(playerActivityRender.getMediaPlayer().isPlaying() ? true : false);
        }
        if (null != canalExt) {
            playerCanalExt.getMediaPlayer().setPause(playerCanalExt.getMediaPlayer().isPlaying() ? true : false);
        }
    }//GEN-LAST:event_PauseButtonActionPerformed

    private void jTextFieldFaceRecorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFaceRecorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFaceRecorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReproductorSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReproductorSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReproductorSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReproductorSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReproductorSec(new File("C:\\prueba_grises\\secuencias\\2\\perspectiva1\\prueba_grises_videoDetect_faceRecorder_1.avi"), new File("C:\\prueba_grises\\secuencias\\2\\perspectiva2\\prueba_grises_videoDetect_activityRender_1.avi"), null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PauseButton;
    private javax.swing.JPanel activityRenderPanel;
    private javax.swing.JPanel canalExtPanel;
    private javax.swing.JButton detButton;
    private javax.swing.JPanel faceRecorderPanel;
    private javax.swing.JButton iniButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldActivityRender;
    private javax.swing.JTextField jTextFieldCanalExterno;
    private javax.swing.JTextField jTextFieldFaceRecorder;
    private javax.swing.JLabel labelActRender;
    private javax.swing.JLabel labelCanalExt;
    private javax.swing.JLabel labelFaceRecorder;
    // End of variables declaration//GEN-END:variables
}
